### ISSUE TITLE
Somewhere is an error

### ISSUE THREAD

**Issue by Chamelllemon** [multimokia/MAS-Submod-Nightmusic#10]
[code]
I'm sorry, but errors were detected in your script. Please correct the
errors listed below, and try again.

File "game/Submods/Night Music/nightmusic.rpy", line 141: invalid syntax
                f"{fp_prefix}{package}"
                                       ^
    

Ren'Py Version: Ren'Py 6.99.12.4.2187
[/code]

**Comment by multimokia** [comment]
Don't install from source, navigate to the releases page and download it from there.

**Comment by Chamelllemon** [comment]
I guess I should have responded sooner, everything works
