### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by PolterGhosty** [multimokia/MAS-Submod-Nightmusic#5]
whenever i open MAS with the submod it gives me this error

[code]
I'm sorry, but errors were detected in your script. Please correct the
errors listed below, and try again.

File "game/Submods/Night Music/nightmusic.rpy", line 141: invalid syntax
                f"{fp_prefix}{package}"
                                       ^
    

Ren'Py Version: Ren'Py 6.99.12.4.2187
[/code]

**Comment by multimokia** [comment]
Don't pull from the source code. That's not actually release ready. As no current build of MAS can handle that syntax. It's preparing for an eventual future build.

Download the mod from the releases page of this repository instead, it will work in your install

**Comment by PolterGhosty** [comment]
Thanks, im still getting used to github
